Form
SatellitesAboveMe/satellitesaboveme.github.io pull request #1
Opened 2022-02-07 17:19 UTC by akechahmadze

Форма для задания локации

2022-02-09 08:57 UTC, k-teplyakov requested changes

2022-02-09 08:57 UTC, k-teplyakov commented on .gitignore
>  npm-debug.log*
давай удалим из репы `build` и добавим ее сюда

2022-02-09 08:57 UTC, k-teplyakov commented on src/apiKey.ts
> +export const n2yoApiKey = 'BFSKBN-KA5QSC-7TKTJY-4UB7'
давай это вынесем в `.env` и подключим либу `dotenv`

2022-02-09 08:57 UTC, k-teplyakov commented on src/Requests/above.ts
> +export const getAboveData = async ({ latitude, longitude, radius, category }: UserFormData): Promise<AboveData> => {
давай переименуем папку `Requests` в `api` и будем здесь группировать функции по источнику

2022-02-09 08:57 UTC, k-teplyakov commented on src/RouteComponents/Main/index.tsx
> +export const Main = () => {
давай переименуем `RouteComponents` в `components`
И договоримся о том, что с большой буквы будем писать только имена файлов, которые содержат имена компонентов

2022-02-09 08:57 UTC, k-teplyakov commented on src/Components/LocationForm/validationScheme.ts
> +  longitude: number().required().min(0),
а у них нет максимального значения?

2022-02-09 08:57 UTC, k-teplyakov commented on src/Components/LocationForm/index.tsx
> +import { satelliteTableStore } from '../../Stores/SatelliteTableStore'
давай использовать абсолютные пути

2022-02-09 08:57 UTC, k-teplyakov commented on src/Components/LocationForm/validationScheme.ts
> +  category: number().required()
наверняка здесь тоже можно проверить валидность категории)

2022-02-09 08:57 UTC, k-teplyakov commented on src/Components/LocationForm/satelliteCategories.ts
> +export const satelliteCategories: SatelliteCategory[] = [
по идее эта информация является частью `api` сервиса, давай туда ее и перенесем

2022-02-09 09:27 UTC, akechahmadze commented on src/RouteComponents/Main/index.tsx
> +export const Main = () => {
@k-teplyakov 
Ок, а сопутствующий файл `index.sccs` как обозвать? А другие файлы, которые рядом лежат? Например, у компонента `LocationForm` рядом есть `validationScheme.ts` и `satelliteCategories.ts`

2022-02-09 09:49 UTC, k-teplyakov commented on src/RouteComponents/Main/index.tsx
> +export const Main = () => {
сопутствующие файлы в нижнем регистре по назначению. например, `scheme.ts` `constants.ts` `index.sccs` etc

2022-02-09 09:53 UTC, akechahmadze commented on src/Components/LocationForm/satelliteCategories.ts
> +export const satelliteCategories: SatelliteCategory[] = [
Почему? По этим данным мы рисуем селект. А сервис принимает лишь `id` и ничего не знает про имя

2022-02-09 10:48 UTC, akechahmadze commented on src/RouteComponents/Main/index.tsx
> +export const Main = () => {
То есть будет выглядеть вот так?
- components
    - Main
        - Main.tsx
        - index.scss
     - SatelliteInfo
         - SatelliteInfo.tsx

Но тогда импорты будут `components/Main/Main`

2022-02-10 09:26 UTC, k-teplyakov commented on src/RouteComponents/Main/index.tsx
> +export const Main = () => {
- components
    - main
        - index.tsx
        - index.scss
     - satelliteInfo
         - index.tsx

2022-02-10 09:28 UTC, akechahmadze commented on src/RouteComponents/Main/index.tsx
> +export const Main = () => {
@k-teplyakov я запутался, а что тогда с большой буквы? )

2022-02-10 09:29 UTC, k-teplyakov commented on src/Components/LocationForm/satelliteCategories.ts
> +export const satelliteCategories: SatelliteCategory[] = [
ну в теории, этот набор данных полностью привязан к api, это их категории
и должен был бы отдаваться каким-то методом апихи, но они его просто опубликовали таблицей

2022-02-10 10:00 UTC, k-teplyakov approved these changes

2022-02-10 10:55 UTC, merged