Satellite table
SatellitesAboveMe/satellitesaboveme.github.io pull request #4
Opened 2022-02-08 11:43 UTC by akechahmadze

Таблица спутников 
closes #2

2022-02-08 11:56 UTC, k-teplyakov requested changes

2022-02-08 11:56 UTC, k-teplyakov commented on src/Stores/SatelliteTableStore.ts
> +    makeAutoObservable(this)
```typescript
makeObservable(this);
```
нам не надо все делать `observable`

2022-02-08 11:56 UTC, k-teplyakov commented on src/Stores/SatelliteTableStore.ts
> +  state?: RequestState
добавь `@observable`

2022-02-08 11:56 UTC, k-teplyakov commented on src/Stores/SatelliteTableStore.ts
> +  async fetchData (userLocation: UserFormData) {
`@action.bound`

2022-02-08 11:56 UTC, k-teplyakov commented on src/Stores/SatelliteTableStore.ts
> +  get satelliteData () {
к геттерам стоит добавлять `@computed`

2022-02-08 11:56 UTC, k-teplyakov commented on src/Stores/SatelliteTableStore.ts
> +export const satelliteTableStore = new SatelliteTableStore()
использование сторов лучше делать через хуки, которые используют контекст, чтобы его всегда можно было подменить при необходимости и убрать ужасную каскадную передачу пропсов

2022-02-08 11:56 UTC, k-teplyakov commented on src/Components/SatellitesTable/index.tsx
> +export const SatelliteTable = () => <SatelliteTableObserver table={satelliteTableStore} />
просто замени на 
```typescript
export default observer(SatelliteTableComponent)
```

2022-02-09 09:29 UTC, k-teplyakov requested changes

2022-02-09 09:29 UTC, k-teplyakov commented on src/Components/LocationForm/index.tsx
> +import { TextField, FormGroup, Button, MenuItem } from '@mui/material'
А зачем тут дублируется код из ветки про форму?

2022-02-09 09:29 UTC, k-teplyakov commented on src/Components/SatellitesTable/index.tsx
> +  const renderTable = () => {
здесь будет уместней использовать `useCallback` или `useMemo`

2022-02-09 09:29 UTC, k-teplyakov commented on src/Components/SatellitesTable/index.tsx
> +    switch (state) {
Давай эту обработку состояния вынесем в `hoc` или хук

2022-02-09 09:39 UTC, akechahmadze commented on src/Components/LocationForm/index.tsx
> +import { TextField, FormGroup, Button, MenuItem } from '@mui/material'
Потому что эта ветка исходит из ветки с формой

2022-02-10 09:24 UTC, k-teplyakov approved these changes

2022-02-10 09:26 UTC, merged