Satellite page
SatellitesAboveMe/satellitesaboveme.github.io pull request #5
Opened 2022-02-10 16:32 UTC by akechahmadze

Страница информации

2022-02-11 09:13 UTC, k-teplyakov requested changes

2022-02-11 09:13 UTC, k-teplyakov commented on src/Components/SatelliteInfo/index.tsx
> +const RenderSatelliteInfo = (props: RenderSatelliteInfoProps) => {
давай этот компонент и тот, который был у таблицы как-то унифицируем и сделаем общим

2022-02-11 09:13 UTC, k-teplyakov commented on src/Utils/parseTLE.ts
> +}
а это зачем? и почему так?

2022-02-11 09:13 UTC, k-teplyakov commented on src/Utils/parseTLE.ts
> +}
тут недостает `trim`

2022-02-11 10:12 UTC, akechahmadze commented on src/Utils/parseTLE.ts
> +}
@k-teplyakov 

Сопоставление названий и property для доступа к ним. Потом это используется как 
`Object.entries(TLEMapping.line2).map(
                          ([name, propertyName]) => (
                                <TableRow key={propertyName}>
                                    <TableCell variant="head">{name}</TableCell>
                                    <TableCell>{(tle.line2)[propertyName]}</TableCell>
                                </TableRow>
                          )
                        )
`

А этот некрасивый тип `type TLEMappingType = {` нужен, чтобы typescript не воспринимал тип объекта `TLEMapping`  как `{ line1: { 'Line Number': string; ... } }`, а именно как `{ line1: { 'Line Number': 'lineNumber'; ... } }` 

Мб можно как-то по-другому)

2022-02-11 10:31 UTC, akechahmadze commented on src/Utils/parseTLE.ts
> +}
@k-teplyakov 

Не думаю. Здесь данные приходят в формате, например вот таком:  `1 25544U 98067A   08264.51782528 -.00002182  00000-0 -11606-4 0  2927`
Документация говорит, что каждый элемент данных занимает отдельный интервал символов. Скажем `Satellite catalog number` это символы **3-7** (*25544*) , а `Classification` это **8** (*U*).  Здесь привязки к пробелам нет

2022-02-11 11:54 UTC, k-teplyakov commented on src/Utils/parseTLE.ts
> +}
Так может развернуть структуру и сделать не `label -> key` и `key -> value`, а `key->label` и `key -> value`?
тогда у тебя будет один тип с дженериком

```typescript
type TLEType<T> = {
  line1: {
    lineNumber: T,
    // ...
  }
}
```

2022-02-11 11:56 UTC, k-teplyakov commented on src/Utils/parseTLE.ts
> +}
да, строка  у тебя получается строго по формату, но значение `25544` может быть `2554` и тогда ты разберешь это как `2554 ` (с пробелом), а это просто часть форматирования, а не значения

2022-02-11 12:04 UTC, akechahmadze commented on src/Utils/parseTLE.ts
> +}
@k-teplyakov 

Не, тогда значение придет как 02554 (по TLE формату пробел туда никак не попадет). Здесь тогда встает вопрос отображать это как число 2554 или же как строчку 02554?

2022-02-15 08:24 UTC, k-teplyakov approved these changes

2022-02-15 08:33 UTC, merged