Notes
SatellitesAboveMe/satellitesaboveme.github.io pull request #8
Opened 2022-02-15 10:25 UTC by akechahmadze

2022-02-15 10:56 UTC, k-teplyakov requested changes

2022-02-15 10:56 UTC, k-teplyakov commented on .eslintrc.js
> +    'only-warn',
зачем это?

2022-02-15 10:56 UTC, k-teplyakov commented on package.json
> +    "eslint-plugin-only-warn": "^1.0.3",
👎

2022-02-15 10:56 UTC, k-teplyakov commented on src/components/notesForm/index.tsx
> +            <Button variant="contained" type="submit" onClick={handleSubmit(onSubmit)}>Save note</Button>
давай повесим обработку формы на саму форму, на событие `onSubmit`

2022-02-15 10:56 UTC, k-teplyakov commented on src/components/satelliteInfo/index.tsx
>    }, [])
не нравится реализация.
что будет отображаться если `id` не в том формате или спутник не будет найден?

2022-02-15 10:56 UTC, k-teplyakov commented on src/components/satelliteNotes/index.tsx
> +  const notes = notesStore.getSatelliteNotes(id)
вот бы сделать так, чтобы отображаемые данные обновлялись, если они были изменены в другой вкладке )

2022-02-15 10:56 UTC, k-teplyakov commented on src/components/satelliteNotes/index.tsx
> +  return (
а что будет отображено, если не получится получить `note`?

2022-02-15 10:56 UTC, k-teplyakov commented on src/components/satelliteNotes/index.tsx
> +const SatelliteNotes = (props: SatelliteNotesProps) => (
а зачем так? что это вообще?

2022-02-15 10:56 UTC, k-teplyakov commented on src/stores/satelliteNotesStore.ts
> +    this.notesStore = observable.map({})
я думаю, что разумней будет написать 
```typescript
@observable.map private notesStore: Map<number, Note[]> = new Map()
```

2022-02-15 10:56 UTC, k-teplyakov commented on src/stores/satelliteNotesStore.ts
> +export const SatelliteNotesStoreContext = createContext<SatelliteNotesStore>(satelliteNotesStore)
сюда можно было бы добавить и хук для доставания значения из контекста, например:
```typescript
export function useSatelliteNotesStore(): SatelliteNotesStore {
    return useContext(SatelliteNotesStoreContext)
}
```

2022-02-16 11:06 UTC, k-teplyakov commented on src/stores/satelliteNotesStore.ts
> +    autorun(() => this.updateLocalStorage())
а зачем нам `autorun`, если мы можем сохранять в `localStorage` в методе добавления ноты?

2022-02-16 11:06 UTC, k-teplyakov commented on src/stores/satelliteNotesStore.ts
> +      const object = JSON.parse(data)
что случится, если `data` оказалась "битая"?

2022-02-16 11:24 UTC, akechahmadze commented on src/stores/satelliteNotesStore.ts
> +    autorun(() => this.updateLocalStorage())
@k-teplyakov 

Метод добавления это же экшн, а запись в `localStorage` это сайд эффект. Мне кажется, их лучше не смешивать 🤔

2022-02-16 11:41 UTC, k-teplyakov commented on src/stores/satelliteNotesStore.ts
> +    autorun(() => this.updateLocalStorage())
разве это сайд эффект?
ты же добавляешь ноту и она должна(!) сохраниться и в сторе и в сторадже, нет?
и даже если идти по этому пути, то помимо `autorun` у тебя есть и другие способы подписаться на события изменения значений: `when` и `reaction`

выбор за тобой :)

2022-02-16 19:40 UTC, k-teplyakov approved these changes

2022-02-17 07:58 UTC, merged